import type { TableBoardState } from "@/types/table";

export const TABLE_PREVIEW_STATE: TableBoardState = {
  tableName: "Replay Surface",
  blindsLabel: "5 / 10",
  potLabel: "55",
  actionLabel: "Waiting for hand input",
  stageLabel: "Preflop reconstruction",
  communityCards: ["--", "--", "--", "--", "--"],
  seats: [
    {
      id: "seat-top",
      name: "UTG Bot",
      stackLabel: "3453",
      betLabel: "10",
      position: "top",
      state: "focused",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-upper-right",
      name: "HJ Bot",
      stackLabel: "8539",
      position: "upperRight",
      state: "waiting",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-mid-right",
      name: "CO Bot",
      stackLabel: "1482",
      betLabel: "40",
      position: "midRight",
      state: "acted",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-lower-right",
      name: "BTN Bot",
      stackLabel: "5094",
      tag: "D",
      position: "lowerRight",
      state: "waiting",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-bottom",
      name: "Hero",
      stackLabel: "1568",
      tag: "You",
      position: "bottom",
      state: "hero",
      holeCards: ["As", "Qh"],
    },
    {
      id: "seat-lower-left",
      name: "SB Bot",
      stackLabel: "2431",
      tag: "SB",
      position: "lowerLeft",
      state: "waiting",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-mid-left",
      name: "BB Bot",
      stackLabel: "1075",
      tag: "BB",
      betLabel: "5",
      position: "midLeft",
      state: "acted",
      holeCards: ["??", "??"],
    },
    {
      id: "seat-upper-left",
      name: "LJ Bot",
      stackLabel: "1771",
      position: "upperLeft",
      state: "waiting",
      holeCards: ["??", "??"],
    },
  ],
  reconstructionHint:
    "Future flow: parse hand description -> map 8 seats -> reconstruct action order -> replay with your existing bot engine.",
};
